// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: marketdata.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_ListMarkets_FullMethodName    = "/marketdata.v1.MarketDataService/ListMarkets"
	MarketDataService_ListLines_FullMethodName      = "/marketdata.v1.MarketDataService/ListLines"
	MarketDataService_GetClosingLine_FullMethodName = "/marketdata.v1.MarketDataService/GetClosingLine"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketDataService exposes the read side of the line store over gRPC.
// The market-data service is the sole writer; paper-trade and other consumers
// call this service instead of connecting directly to the database.
type MarketDataServiceClient interface {
	// ListMarkets returns the distinct set of market IDs that have at least one saved line.
	ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (*ListMarketsResponse, error)
	// ListLines returns all stored lines for the given market, ordered by recorded_at descending.
	ListLines(ctx context.Context, in *ListLinesRequest, opts ...grpc.CallOption) (*ListLinesResponse, error)
	// GetClosingLine returns the most recent closing line for the given market and side.
	// The line field is absent from the response if no closing line exists.
	GetClosingLine(ctx context.Context, in *GetClosingLineRequest, opts ...grpc.CallOption) (*GetClosingLineResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (*ListMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMarketsResponse)
	err := c.cc.Invoke(ctx, MarketDataService_ListMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) ListLines(ctx context.Context, in *ListLinesRequest, opts ...grpc.CallOption) (*ListLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinesResponse)
	err := c.cc.Invoke(ctx, MarketDataService_ListLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetClosingLine(ctx context.Context, in *GetClosingLineRequest, opts ...grpc.CallOption) (*GetClosingLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClosingLineResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetClosingLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// MarketDataService exposes the read side of the line store over gRPC.
// The market-data service is the sole writer; paper-trade and other consumers
// call this service instead of connecting directly to the database.
type MarketDataServiceServer interface {
	// ListMarkets returns the distinct set of market IDs that have at least one saved line.
	ListMarkets(context.Context, *ListMarketsRequest) (*ListMarketsResponse, error)
	// ListLines returns all stored lines for the given market, ordered by recorded_at descending.
	ListLines(context.Context, *ListLinesRequest) (*ListLinesResponse, error)
	// GetClosingLine returns the most recent closing line for the given market and side.
	// The line field is absent from the response if no closing line exists.
	GetClosingLine(context.Context, *GetClosingLineRequest) (*GetClosingLineResponse, error)
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) ListMarkets(context.Context, *ListMarketsRequest) (*ListMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMarkets not implemented")
}
func (UnimplementedMarketDataServiceServer) ListLines(context.Context, *ListLinesRequest) (*ListLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLines not implemented")
}
func (UnimplementedMarketDataServiceServer) GetClosingLine(context.Context, *GetClosingLineRequest) (*GetClosingLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClosingLine not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_ListMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).ListMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_ListMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).ListMarkets(ctx, req.(*ListMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_ListLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).ListLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_ListLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).ListLines(ctx, req.(*ListLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetClosingLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClosingLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetClosingLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetClosingLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetClosingLine(ctx, req.(*GetClosingLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketdata.v1.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMarkets",
			Handler:    _MarketDataService_ListMarkets_Handler,
		},
		{
			MethodName: "ListLines",
			Handler:    _MarketDataService_ListLines_Handler,
		},
		{
			MethodName: "GetClosingLine",
			Handler:    _MarketDataService_GetClosingLine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketdata.proto",
}
