// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: marketdata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsRequest) Reset() {
	*x = ListMarketsRequest{}
	mi := &file_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsRequest) ProtoMessage() {}

func (x *ListMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketsRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{0}
}

type ListMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketIds     []string               `protobuf:"bytes,1,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsResponse) Reset() {
	*x = ListMarketsResponse{}
	mi := &file_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsResponse) ProtoMessage() {}

func (x *ListMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketsResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *ListMarketsResponse) GetMarketIds() []string {
	if x != nil {
		return x.MarketIds
	}
	return nil
}

type ListLinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinesRequest) Reset() {
	*x = ListLinesRequest{}
	mi := &file_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinesRequest) ProtoMessage() {}

func (x *ListLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinesRequest.ProtoReflect.Descriptor instead.
func (*ListLinesRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *ListLinesRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type ListLinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*Line                `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinesResponse) Reset() {
	*x = ListLinesResponse{}
	mi := &file_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinesResponse) ProtoMessage() {}

func (x *ListLinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinesResponse.ProtoReflect.Descriptor instead.
func (*ListLinesResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *ListLinesResponse) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

type GetClosingLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClosingLineRequest) Reset() {
	*x = GetClosingLineRequest{}
	mi := &file_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClosingLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClosingLineRequest) ProtoMessage() {}

func (x *GetClosingLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClosingLineRequest.ProtoReflect.Descriptor instead.
func (*GetClosingLineRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *GetClosingLineRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetClosingLineRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

type GetClosingLineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// absent when no closing line exists for this market/side combination
	Line          *Line `protobuf:"bytes,1,opt,name=line,proto3,oneof" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClosingLineResponse) Reset() {
	*x = GetClosingLineResponse{}
	mi := &file_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClosingLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClosingLineResponse) ProtoMessage() {}

func (x *GetClosingLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClosingLineResponse.ProtoReflect.Descriptor instead.
func (*GetClosingLineResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *GetClosingLineResponse) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

// Line is a single price offered by one bookmaker for one side of a market at a moment in time.
type Line struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MarketId       string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BookId         string                 `protobuf:"bytes,4,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Side           string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	Label          string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	AmericanOdds   int32                  `protobuf:"varint,7,opt,name=american_odds,json=americanOdds,proto3" json:"american_odds,omitempty"`
	DecimalOdds    float64                `protobuf:"fixed64,8,opt,name=decimal_odds,json=decimalOdds,proto3" json:"decimal_odds,omitempty"`
	RawImpliedProb float64                `protobuf:"fixed64,9,opt,name=raw_implied_prob,json=rawImpliedProb,proto3" json:"raw_implied_prob,omitempty"`
	ImpliedProb    float64                `protobuf:"fixed64,10,opt,name=implied_prob,json=impliedProb,proto3" json:"implied_prob,omitempty"`
	Spread         *float64               `protobuf:"fixed64,11,opt,name=spread,proto3,oneof" json:"spread,omitempty"`
	Total          *float64               `protobuf:"fixed64,12,opt,name=total,proto3,oneof" json:"total,omitempty"`
	RecordedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	IsClosing      bool                   `protobuf:"varint,14,opt,name=is_closing,json=isClosing,proto3" json:"is_closing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *Line) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Line) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Line) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Line) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Line) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Line) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Line) GetAmericanOdds() int32 {
	if x != nil {
		return x.AmericanOdds
	}
	return 0
}

func (x *Line) GetDecimalOdds() float64 {
	if x != nil {
		return x.DecimalOdds
	}
	return 0
}

func (x *Line) GetRawImpliedProb() float64 {
	if x != nil {
		return x.RawImpliedProb
	}
	return 0
}

func (x *Line) GetImpliedProb() float64 {
	if x != nil {
		return x.ImpliedProb
	}
	return 0
}

func (x *Line) GetSpread() float64 {
	if x != nil && x.Spread != nil {
		return *x.Spread
	}
	return 0
}

func (x *Line) GetTotal() float64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *Line) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *Line) GetIsClosing() bool {
	if x != nil {
		return x.IsClosing
	}
	return false
}

var File_marketdata_proto protoreflect.FileDescriptor

const file_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x10marketdata.proto\x12\rmarketdata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12ListMarketsRequest\"4\n" +
	"\x13ListMarketsResponse\x12\x1d\n" +
	"\n" +
	"market_ids\x18\x01 \x03(\tR\tmarketIds\"/\n" +
	"\x10ListLinesRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\">\n" +
	"\x11ListLinesResponse\x12)\n" +
	"\x05lines\x18\x01 \x03(\v2\x13.marketdata.v1.LineR\x05lines\"H\n" +
	"\x15GetClosingLineRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\"O\n" +
	"\x16GetClosingLineResponse\x12,\n" +
	"\x04line\x18\x01 \x01(\v2\x13.marketdata.v1.LineH\x00R\x04line\x88\x01\x01B\a\n" +
	"\x05_line\"\xcf\x03\n" +
	"\x04Line\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12\x17\n" +
	"\abook_id\x18\x04 \x01(\tR\x06bookId\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12#\n" +
	"\ramerican_odds\x18\a \x01(\x05R\famericanOdds\x12!\n" +
	"\fdecimal_odds\x18\b \x01(\x01R\vdecimalOdds\x12(\n" +
	"\x10raw_implied_prob\x18\t \x01(\x01R\x0erawImpliedProb\x12!\n" +
	"\fimplied_prob\x18\n" +
	" \x01(\x01R\vimpliedProb\x12\x1b\n" +
	"\x06spread\x18\v \x01(\x01H\x00R\x06spread\x88\x01\x01\x12\x19\n" +
	"\x05total\x18\f \x01(\x01H\x01R\x05total\x88\x01\x01\x12;\n" +
	"\vrecorded_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12\x1d\n" +
	"\n" +
	"is_closing\x18\x0e \x01(\bR\tisClosingB\t\n" +
	"\a_spreadB\b\n" +
	"\x06_total2\x98\x02\n" +
	"\x11MarketDataService\x12T\n" +
	"\vListMarkets\x12!.marketdata.v1.ListMarketsRequest\x1a\".marketdata.v1.ListMarketsResponse\x12N\n" +
	"\tListLines\x12\x1f.marketdata.v1.ListLinesRequest\x1a .marketdata.v1.ListLinesResponse\x12]\n" +
	"\x0eGetClosingLine\x12$.marketdata.v1.GetClosingLineRequest\x1a%.marketdata.v1.GetClosingLineResponseBBZ@github.com/jedi-knights/sports-betting/internal/marketdata/pb;pbb\x06proto3"

var (
	file_marketdata_proto_rawDescOnce sync.Once
	file_marketdata_proto_rawDescData []byte
)

func file_marketdata_proto_rawDescGZIP() []byte {
	file_marketdata_proto_rawDescOnce.Do(func() {
		file_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)))
	})
	return file_marketdata_proto_rawDescData
}

var file_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_marketdata_proto_goTypes = []any{
	(*ListMarketsRequest)(nil),     // 0: marketdata.v1.ListMarketsRequest
	(*ListMarketsResponse)(nil),    // 1: marketdata.v1.ListMarketsResponse
	(*ListLinesRequest)(nil),       // 2: marketdata.v1.ListLinesRequest
	(*ListLinesResponse)(nil),      // 3: marketdata.v1.ListLinesResponse
	(*GetClosingLineRequest)(nil),  // 4: marketdata.v1.GetClosingLineRequest
	(*GetClosingLineResponse)(nil), // 5: marketdata.v1.GetClosingLineResponse
	(*Line)(nil),                   // 6: marketdata.v1.Line
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_marketdata_proto_depIdxs = []int32{
	6, // 0: marketdata.v1.ListLinesResponse.lines:type_name -> marketdata.v1.Line
	6, // 1: marketdata.v1.GetClosingLineResponse.line:type_name -> marketdata.v1.Line
	7, // 2: marketdata.v1.Line.recorded_at:type_name -> google.protobuf.Timestamp
	0, // 3: marketdata.v1.MarketDataService.ListMarkets:input_type -> marketdata.v1.ListMarketsRequest
	2, // 4: marketdata.v1.MarketDataService.ListLines:input_type -> marketdata.v1.ListLinesRequest
	4, // 5: marketdata.v1.MarketDataService.GetClosingLine:input_type -> marketdata.v1.GetClosingLineRequest
	1, // 6: marketdata.v1.MarketDataService.ListMarkets:output_type -> marketdata.v1.ListMarketsResponse
	3, // 7: marketdata.v1.MarketDataService.ListLines:output_type -> marketdata.v1.ListLinesResponse
	5, // 8: marketdata.v1.MarketDataService.GetClosingLine:output_type -> marketdata.v1.GetClosingLineResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_marketdata_proto_init() }
func file_marketdata_proto_init() {
	if File_marketdata_proto != nil {
		return
	}
	file_marketdata_proto_msgTypes[5].OneofWrappers = []any{}
	file_marketdata_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_proto_rawDesc), len(file_marketdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_proto_goTypes,
		DependencyIndexes: file_marketdata_proto_depIdxs,
		MessageInfos:      file_marketdata_proto_msgTypes,
	}.Build()
	File_marketdata_proto = out.File
	file_marketdata_proto_goTypes = nil
	file_marketdata_proto_depIdxs = nil
}
